#include "theme_presets.h"

const QString themePresets::light{
	"QMainWindow { background-color: white; }"
/*---------------------------------------------*/
	"QMenuBar {"
	"    background-color: #E6EAEF;"
	"    color: black;"
	"    border: 2px solid #D7E1EA;"
	"    border-radius: 4px;"
	"}"
	"QMenuBar::item:selected {"
	"    background-color: #F6F8FA;"
	"    border: 1px solid #818B98;"
	"    border-radius: 2px;"
	"}"
	"QMenu {"
	"    background-color: #D7E1EA;"
	"    color: black;"
	"    border: 1px solid #D1D9E0;"
	"}"
	"QMenu::item:selected {"
	"    background-color: #818B98;"
	"    border: 2px solid #818B98;"
	"    border-radius: 4px;"
	"}"
/*---------------------------------------------*/
	"QToolBar {"
	"    background-color: #818B98;"
	"    border: 2px solid #565C63;"
	"    border-radius: 6px;"
	"}"
	"QToolButton {"
	"    background-color: transparent;"
	"	 padding: 1px;"//avoid move on push effect
	"    border-radius: 4px;"
	"}"
	"QToolButton:hover {"
	"    background-color: #60656C;"
	"    border-radius: 4px;"
	"}"
	"QToolButton:pressed {"
	"    background-color: #37393D;"
	"    border-radius: 4px;"
	"}"
	"QToolButton:checked {"
	"    background-color: #37393D;"
	"    border-radius: 4px;"
	"}"
/*---------------------------------------------*/
	"QDialog { background-color: #E0E0E0; }"
	"QLabel { color: black; }"
/*---------------------------------------------*/
	"QSpinBox {"
	"    background-color: #D7E1EA;"
	"    color: black;"
	"    border: 1px solid #505050;"
	"    border-radius: 4px;"
	"    padding: 2px;"
	"}"
	"QSpinBox::up-button {"
	"    background-color: #818B98;"
	"    border-radius: 2px;"
	"    padding: 2px;"
	"    image: url(icons/arrow_up.png);"
	"}"
	"QSpinBox::down-button {"
	"    background-color: #818B98;"
	"    border-radius: 2px;"
	"    padding: 2px;"
	"    image: url(icons/arrow_down.png);"
	"}"
	"QSpinBox::up-button:hover { background-color: #565C63; }"
	"QSpinBox::down-button:hover { background-color: #565C63; }"
/*---------------------------------------------*/
	"QComboBox {"
	"    background-color: #D7E1EA;"
	"    color: black;"
	"    border: 1px solid #505050;"
	"    border-radius: 4px;"
	"}"
	"QComboBox QAbstractItemView {"
	"    background-color: #D7E1EA;"
	"    selection-background-color: #818B98;"
	"    selection-color: black;"
	"    color: black;"
	"    border: 1px solid #505050;"
	"}"
	"QComboBox::drop-down {"
	"    background-color: #818B98;"
	"    border-radius: 2px;"
	"    padding: 1px;"
	"}"
	"QComboBox::drop-down:hover { background-color: #565C63; }"
	"QComboBox::down-arrow { image: url(icons/arrow_down.png); }"
/*---------------------------------------------*/
	"QPushButton {"
	"    background-color: #E6EAEF;"
	"    color: black;"
	"    border: 1px solid #D7E1EA;"
	"    border-radius: 4px;"
	"}"
	"QPushButton:hover {"
	"    background-color: #F6F8FA;"
	"    border: 1px solid #818B98;"
	"}"
/*---------------------------------------------*/
	"QSlider::groove:horizontal {"
	"    height: 4px;"
	"    background-color: #E6EAEF;"
	"    border: 1px solid #D7E1EA;"
	"    border-radius: 2px;"
	"}"
	"QSlider::handle:horizontal {"
	"    background-color: #D7E1EA;"
	"    border: 1px solid #D1D9E0;"
	"    width: 8px;"
	"    margin: -4px 0;"//
	"    border-radius: 2px;"
	"}"
	"QSlider::handle:horizontal:hover {"
	"    background-color: #F6F8FA;"
	"    border: 1px solid #818B98;"
	"}"
	"QLineEdit {"
	"    background-color: #D7E1EA;"
	"    color: black;"
	"    border: 1px solid #505050;"
	"    border-radius: 2px;"
	"    padding: 2px;"
	"}"
};