#include "theme_presets.h"

const QString themePresets::light{
	"QMainWindow { background-color: #FFFFFF; }"
	//"QPushButton { color: black; background-color: #4CAF50; }"
	//"QPushButton:hover { background-color: #367C39; }"
	"QMenuBar {"
	"    background-color: #E6EAEF;"
	"    color: black;"
	"    border: 2px solid #D7E1EA;"
	"}"
	"QMenuBar::item:selected {"
	"    background-color: #F6F8FA;"
	"    border: 1px solid #818B98;"
	"    border-radius: 2px;"
	"}"
	"QMenu {"
	"    background-color: #D7E1EA;"
	"    color: black;"
	"    border: 1px solid #D1D9E0;"
	"}"
	"QMenu::item:selected {"
	"    background-color: #818B98;"
	"    border: 2px solid #818B98;"
	"    border-radius: 4px;"
	"}"
/*---------------------------------------------*/
	"QToolBar {"
	"    background-color: #818B98;"
	"    border: 2px solid #565C63;"
	"}"
	"QToolButton {"
	"    background-color: transparent;"
	"	 padding: 1px;"//avoid move on push effect
	"    border-radius: 4px;"
	"}"
	"QToolButton:hover {"
	"    background-color: #60656C;"
	"    border-radius: 4px;"
	"}"
	"QToolButton:pressed {"
	"    background-color: #37393D;"
	"    border-radius: 4px;"
	"}"

};